### ISSUE TITLE
어드민페이지 UI 디자인 변경

### ISSUE THREAD

**Issue by blue7918** [TeamProject-Farmer/front-end#18]
## Description
어드민 페이지 새로운 디자인 적용

## Todo
- [ ] 공통된 스타일 묶어서 활용하기
- [ ] 홈
- [ ] 주문
- [ ] 상품
- [ ] 회원
- [ ] 게시판
- [ ] 프로모션

**Comment by hyeone999** [comment]
어드민페이지 구현 변경으로 인해 해당 issue close합니다!
