### ISSUE TITLE
어드민 페이지 UI 구현

### ISSUE THREAD

**Issue by blue7918** [TeamProject-Farmer/front-end#6]
## Description
어드민 페이지 UI 구현

## Todo
- [x] 모달 제외한 UI 리펙토링
- [x] 변수명 통일하기
- [x] 모달 완성하기

## ETC

**Comment by hyeone999** [comment]
윤형님! label 항상 확인 부탁드려요!
+ assigned 본인으로 해주시면 되고, project 추가 부탁드립니다 :)

**Comment by blue7918** [comment]
아...! project 만들기 전에 test로 만들었었어요...! 바꿔주셔서 감사합니다 ㅎㅎ
